import Container from "@/components/layout/Container";
import SideNav from "@/components/navigation/sidebar/SideNav";
import TopBar from "@/components/navigation/topbar/TopBar";
import type { Metadata } from "next";
import localFont from "next/font/local";
import '@/assets/styles/global/global.scss';

const montserratRegular = localFont({
  src: "./fonts/Montserrat-Regular.ttf",
  variable: "--font-montserrat-regular",
  weight: "100 900",
});
const montserratBold = localFont({
  src: "./fonts/Montserrat-Bold.ttf",
  variable: "--font-montserrat-bold",
  weight: "100 900",
});

const poppinsRegular = localFont({
    src: "./fonts/Poppins-Regular.ttf",
    variable: "--font-poppins",
    weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserratRegular} ${montserratBold} ${poppinsRegular}`}>
        <SideNav />
        <TopBar />
        <Container>
            {children}
        </Container>
      </body>
    </html>
  );
}
